name: Deploy AWS on main branch

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_job_template.yaml
    permissions:
      id-token: write
      checks: read
      contents: read
      pull-requests: write
    with:
      pr-number: main
      stack-name: CITERA-Chatbot-back-main
      s3-dir: main
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
